name = "helpspeaking-downloader"
compatibility_date = "2025-08-23"
main = "./src/index.ts"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "KV"
id = "4e9f2826ba9344d49893cb8c53e474e3"

[browser]
binding = "BROWSER"

[triggers]
crons = ["0 0 * * *"]
